//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms_Tester
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptFix
    {
        public int Id { get; set; }
        public int ReceiptId { get; set; }
        public string Date { get; set; }
        public string Comapany_Name { get; set; }
        public string Tax_Identification { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string Receipt_Attached { get; set; }
        public string Receipt_Name { get; set; }
        public string BusinessReason { get; set; }
        public string NameOfIndividual { get; set; }
        public string Project { get; set; }
        public string Amount { get; set; }
        public bool IsAuthenticated { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    }
}
