//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiRocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableStatu
    {
        public int Id { get; set; }
        public int MaxValue { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<System.DateTime> LastStart { get; set; }
        public Nullable<int> TotalConvert { get; set; }
        public string Status { get; set; }
        public string CurrentFolder { get; set; }
        public Nullable<int> LastBatchCount { get; set; }
    }
}
